### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by jukefr** [lpaicheur/portfolio#43]
Hello,

I cannot find how to make this project work....

Please add a readme or some sort of documentation.

Thank you very much.

**Comment by jukefr** [comment]
:+1:

**Comment by lpaicheur** [comment]
Hello,

For a fullstack developer like you, a quick look to the package.json should be enough to understand how the project works. However, I understand that it can be a little complicated when you are beginning and I do not want you to be lost, therefore I created a README.md at the root of the project.

Have a great day.

**Comment by jukefr** [comment]
yes it is indeed important to consider that some people are way less knowledgeable than others, thank you.
